code_name = {
    [1] = "LBUTTON",     -- Left mouse button
    [2] = "RBUTTON",     -- Right mouse button
    [3] = "CANCEL",     -- Control-break processing
    [4] = "MBUTTON",     -- Middle mouse button (three-button mouse)
    [5] = "XBUTTON1",     -- Windows 2000/XP: X1 mouse button
    [6] = "XBUTTON2",     -- Windows 2000/XP: X2 mouse button
    [8] = "BACK",     -- BACKSPACE key
    [9] = "TAB",     -- TAB key
    [12] = "CLEAR",     -- CLEAR key
    [13] = "RETURN",     -- ENTER key
    [16] = "SHIFT",     -- SHIFT key
    [17] = "CTRL",     -- CTRL key
    [18] = "ALT",     -- ALT key
    [19] = "PAUSE",     -- PAUSE key
    [20] = "CAPSLOCK",     -- CAPS LOCK key
    [21] = "KANA",     -- Input Method Editor (IME) Kana mode
    [21] = "HANGUL",     -- IME Hangul mode
    [23] = "JUNJA",     -- IME Junja mode
    [24] = "FINAL",     -- IME final mode
    [25] = "KANJI",     -- IME Kanji mode
    [27] = "ESCAPE",     -- ESC key
    [28] = "CONVERT",     -- IME convert
    [29] = "NONCONVERT",     -- IME nonconvert
    [30] = "ACCEPT",     -- IME accept
    [31] = "MODECHANGE",     -- IME mode change request
    [32] = "SPACE",     -- SPACEBAR
    [33] = "PRIOR",     -- PAGE UP key
    [34] = "NEXT",     -- PAGE DOWN key
    [35] = "END",     -- END key
    [36] = "HOME",     -- HOME key
    [37] = "LEFT",     -- LEFT ARROW key
    [38] = "UP",     -- UP ARROW key
    [39] = "RIGHT",     -- RIGHT ARROW key
    [40] = "DOWN",     -- DOWN ARROW key
    [41] = "SELECT",     -- SELECT key
    [42] = "PRINT",     -- PRINT key
    [43] = "EXECUTE",     -- EXECUTE key
    [44] = "SNAPSHOT",     -- PRINT SCREEN key
    [45] = "INSERT",     -- INS key
    [46] = "DELETE",     -- DEL key
    [47] = "HELP",     -- HELP key
    [91] = "LWIN",     -- Left Windows key (Microsoft Natural keyboard) 
    [92] = "RWIN",     -- Right Windows key (Natural keyboard)
    [93] = "APPS",     -- Applications key (Natural keyboard)
    [95] = "SLEEP",     -- Computer Sleep key
    [96] = "NUMPAD0",     -- Numeric keypad 0 key
    [97] = "NUMPAD1",     -- Numeric keypad 1 key
    [98] = "NUMPAD2",     -- Numeric keypad 2 key
    [99] = "NUMPAD3",     -- Numeric keypad 3 key
    [100] = "NUMPAD4",     -- Numeric keypad 4 key
    [101] = "NUMPAD5",     -- Numeric keypad 5 key
    [102] = "NUMPAD6",     -- Numeric keypad 6 key
    [103] = "NUMPAD7",     -- Numeric keypad 7 key
    [104] = "NUMPAD8",     -- Numeric keypad 8 key
    [105] = "NUMPAD9",     -- Numeric keypad 9 key
    [106] = "MULTIPLY",     -- Multiply key
    [107] = "ADD",     -- Add key
    [108] = "SEPARATOR",     -- Separator key
    [109] = "SUBTRACT",     -- Subtract key
    [110] = "DECIMAL",     -- Decimal key
    [111] = "DIVIDE",     -- Divide key
    [112] = "F1",     -- F1 key
    [113] = "F2",     -- F2 key
    [114] = "F3",     -- F3 key
    [115] = "F4",     -- F4 key
    [116] = "F5",     -- F5 key
    [117] = "F6",     -- F6 key
    [118] = "F7",     -- F7 key
    [119] = "F8",     -- F8 key
    [120] = "F9",     -- F9 key
    [121] = "F10",     -- F10 key
    [122] = "F11",     -- F11 key
    [123] = "F12",     -- F12 key
    [124] = "F13",     -- F13 key
    [125] = "F14",     -- F14 key
    [126] = "F15",     -- F15 key
    [127] = "F16",     -- F16 key
    [144] = "NUMLOCK",     -- NUM LOCK key
    [145] = "SCROLL",     -- SCROLL LOCK key
    [160] = "LSHIFT",     -- Left SHIFT key
    [161] = "RSHIFT",     -- Right SHIFT key
    [162] = "LCTRL",     -- Left CTRL key
    [163] = "RCTRL",     -- Right CTRL key
    [164] = "LALT",     -- Left ALT key
    [165] = "RALT",     -- Right ALT key
    [166] = "BROWSER_BACK",     -- Windows 2000/XP: Browser Back key
    [167] = "BROWSER_FORWARD",     -- Windows 2000/XP: Browser Forward key
    [168] = "BROWSER_REFRESH",     -- Windows 2000/XP: Browser Refresh key
    [169] = "BROWSER_STOP",     -- Windows 2000/XP: Browser Stop key
    [170] = "BROWSER_SEARCH",     -- Windows 2000/XP: Browser Search key 
    [171] = "BROWSER_FAVORITES",     -- Windows 2000/XP: Browser Favorites key
    [172] = "BROWSER_HOME",     -- Windows 2000/XP: Browser Start and Home key
    [173] = "VOLUME_MUTE",     -- Windows 2000/XP: Volume Mute key
    [174] = "VOLUME_DOWN",     -- Windows 2000/XP: Volume Down key
    [175] = "VOLUME_UP",     -- Windows 2000/XP: Volume Up key
    [176] = "MEDIA_NEXT_TRACK",     -- Windows 2000/XP: Next Track key
    [177] = "MEDIA_PREV_TRACK",     -- Windows 2000/XP: Previous Track key
    [178] = "MEDIA_STOP",     -- Windows 2000/XP: Stop Media key
    [179] = "MEDIA_PLAY_PAUSE",     -- Windows 2000/XP: Play/Pause Media key
    [180] = "LAUNCH_MAIL",     -- Windows 2000/XP: Start Mail key
    [181] = "LAUNCH_MEDIA_SELECT",     -- Windows 2000/XP: Select Media key
    [182] = "LAUNCH_APP1",     -- Windows 2000/XP: Start Application 1 key
    [183] = "LAUNCH_APP2",     -- Windows 2000/XP: Start Application 2 key
    [186] = "OEM_1",     -- Used for miscellaneous characters; it can vary by keyboard.
    [187] = "OEM_PLUS",     -- Windows 2000/XP: For any country/region, the '+' key
    [188] = "OEM_COMMA",     -- Windows 2000/XP: For any country/region, the ',' key
    [189] = "OEM_MINUS",     -- Windows 2000/XP: For any country/region, the '-' key
    [190] = "OEM_PERIOD",     -- Windows 2000/XP: For any country/region, the '.' key
    [191] = "OEM_2",     -- Used for miscellaneous characters; it can vary by keyboard.
    [192] = "OEM_3",     -- Used for miscellaneous characters; it can vary by keyboard. 
    [219] = "OEM_4",     -- Used for miscellaneous characters; it can vary by keyboard. 
    [220] = "OEM_5",     -- Used for miscellaneous characters; it can vary by keyboard. 
    [221] = "OEM_6",     -- Used for miscellaneous characters; it can vary by keyboard. 
    [222] = "OEM_7",     -- Used for miscellaneous characters; it can vary by keyboard. 
    [223] = "OEM_8",     -- Used for miscellaneous characters; it can vary by keyboard.
    [226] = "OEM_102",     -- Windows 2000/XP: Either the angle bracket key or the backslash key on the RT 102-key keyboard
    [229] = "PROCESSKEY",     -- Windows 95/98/Me, Windows NT 4.0, Windows 2000/XP: IME PROCESS key
    [231] = "PACKET",     -- Windows 2000/XP: Used to pass Unicode characters as if they were keystrokes. The VK_PACKET key is the low word of a 32-bit Virtual Key value used for non-keyboard input methods. For more information, see Remark in KEYBDINPUT, SendInput, WM_KEYDOWN, and WM_KEYUP
    [246] = "ATTN",     -- Attn key
    [247] = "CRSEL",     -- CrSel key
    [248] = "EXSEL",     -- ExSel key
    [249] = "EREOF",     -- Erase EOF key
    [250] = "PLAY",     -- Play key
    [251] = "ZOOM",     -- Zoom key
    [252] = "NONAME",     -- Reserved 
    [253] = "PA1",     -- PA1 key
    [254] = "OEM_CLEAR",     -- Clear key
    [48] = "0",
    [49] = "1",
    [50] = "2",
    [51] = "3",
    [52] = "4",
    [53] = "5",
    [54] = "6",
    [55] = "7",
    [56] = "8",
    [57] = "9",
    [65] = "A",
    [66] = "B",
    [67] = "C",
    [68] = "D",
    [69] = "E",
    [70] = "F",
    [71] = "G",
    [72] = "H",
    [73] = "I",
    [74] = "J",
    [75] = "K",
    [76] = "L",
    [77] = "M",
    [78] = "N",
    [79] = "O",
    [80] = "P",
    [81] = "Q",
    [82] = "R",
    [83] = "S",
    [84] = "T",
    [85] = "U",
    [86] = "V",
    [87] = "W",
    [88] = "X",
    [89] = "Y",
    [90] = "Z",
}